# This workflow will scrap GitHub trending projects daily.
name: Daily Update Rules
#每三天运行一次

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 */7 * *"


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scraper
      run: |
        python main.py

    - name: Check for changes
      id: git-status
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"
      continue-on-error: true

    # Runs a set of commands using the runners shell
    - name: Push to origin master
      if: steps.git-status.outputs.changed == 'true'
      run: |
        echo start push
        git config --global user.name "fireinrain"
        git config --global user.email "lzyme.dev@gmail.com"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push
